// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageModelPromptMessage } from "./LanguageModelPromptMessage";
import type { ReasoningEffort } from "./ReasoningEffort";
import type { ResponseFormat } from "./ResponseFormat";
import type { TimeoutConfiguration } from "./TimeoutConfiguration";
import type { Tool } from "./Tool";
import type { ToolChoice } from "./ToolChoice";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Options passed to `LanguageModel::do_generate` / `do_stream`.
 *
 * This is the **provider-facing** options struct. Users interact with
 * `GenerateTextOptions` (user-facing) which is converted to `CallOptions`
 * by the `generate_text` / `stream_text` functions.
 */
export type CallOptions = { 
/**
 * The standardized prompt (message array). Required.
 */
prompt: Array<LanguageModelPromptMessage>, 
/**
 * Maximum tokens to generate.
 */
max_output_tokens: number | null, 
/**
 * Sampling temperature.
 */
temperature: number | null, 
/**
 * Stop sequences.
 */
stop_sequences: Array<string> | null, 
/**
 * Nucleus sampling `top_p`.
 */
top_p: number | null, 
/**
 * Top-k sampling.
 */
top_k: number | null, 
/**
 * Presence penalty.
 */
presence_penalty: number | null, 
/**
 * Frequency penalty.
 */
frequency_penalty: number | null, 
/**
 * Response format (text or JSON).
 */
response_format: ResponseFormat | null, 
/**
 * Seed for reproducibility.
 */
seed: number | null, 
/**
 * Tools available to the model (function tools and/or provider-defined tools).
 */
tools: Array<Tool> | null, 
/**
 * How the model should choose tools.
 */
tool_choice: ToolChoice, 
/**
 * Extra HTTP headers.
 */
headers: { [key in string]: string } | null, 
/**
 * Provider-specific options (keyed by provider name).
 */
provider_options: { [key in string]: JsonValue } | null, 
/**
 * Top-level reasoning effort. Maps to OpenAI `reasoning_effort` and
 * Anthropic `thinking` config.
 */
reasoning: ReasoningEffort | null, 
/**
 * Per-call request body overrides. Deep-merged into the provider-built
 * request body (after any built-in vendor override) before sending.
 * `null` values delete the corresponding key. See RFC-0017.
 */
body_overrides: JsonValue | null, 
/**
 * Per-call retry count override. `None` uses the provider's configured
 * Core operation retry. `Some(0)` disables retries.
 */
max_retries: number | null, 
/**
 * Per-call timeout configuration (total / first-chunk / chunk idle).
 * `None` = no timeouts (provider defaults still apply at the HTTP layer).
 */
timeout: TimeoutConfiguration | null, 
/**
 * Session identifier, for grouping consecutive calls into a session
 * (observability, see RFC-0024). Explicit values take precedence; when
 * `None` and the optional session inferer is enabled, one may be inferred.
 * Orthogonal to RFC-0019 session-affinity headers: this field is for
 * local grouping, while session headers in `headers` are for upstream
 * routing — both may share an id value but travel different paths.
 */
session_id: string | null, 
/**
 * Emit raw provider stream chunks as `StreamPart::Raw` (debugging aid).
 * When `Some(true)`, streaming providers yield one `Raw` part per JSON
 * SSE event, carrying the **parsed JSON payload** of the event, emitted
 * before the parsed parts. Excludes the `[DONE]` sentinel; unparsable
 * chunks emit only `Error`. `null`/`Some(false)` = off.
 * Currently honored by the OpenAI-compatible family (openai / azure /
 * openai-compatible registry providers) and by the Anthropic family
 * (anthropic / anthropic-aws; the Vertex MaaS Anthropic wrapper rides the
 * OpenAI-compatible path); other provider families ignore it for now
 * (RFC-0016 M2).
 */
include_raw_chunks: boolean | null, };
