// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Provider-facing tool call before Core parses and validates its input.
 *
 * The wire shape matches [`ToolCall`] field for field, except that `input`
 * is the provider's raw argument *text* rather than a parsed value.
 */
export type RawToolCall = { tool_call_id: string, tool_name: string, input: string, provider_executed?: boolean | null, dynamic?: boolean | null, thought_signature?: string | null, provider_metadata?: JsonValue | null, };
