// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RawToolCall } from "./RawToolCall";

/**
 * A host's answer to one tool-call repair request.
 *
 * The bindings cannot carry a [`ToolCallRepair`] closure, so a host instead
 * reads the invalid call off the result, repairs it in its own language, and
 * hands the answer back as this value. Wire shape:
 * `{"type":"repaired","tool_call":{…}}`, `{"type":"unchanged"}`, or
 * `{"type":"failed","message":"…"}`.
 */
export type ToolCallRepairReply = { "type": "repaired", tool_call: RawToolCall, } | { "type": "unchanged" } | { "type": "failed", message: string, };
