"""Typed wrapper for the aimux Python binding.

This layer sits *on top* of the native PyO3 ``Model.generate_text`` /
``Model.stream_text`` methods (which exchange JSON strings) and exposes a
typed API: inputs and outputs are Pydantic models / native Python objects, so
callers never have to ``json.dumps`` / ``json.loads`` by hand.

The native (raw) JSON-string API in :mod:`aimux` is left untouched — this
module is an additional, optional layer::

    from aimux.wrapper import generate_text, GenerateTextOptions, ModelMessage

The Pydantic models mirror the Rust core types in ``aimux-core/src/`` (see
``bindings/node/src/types/*.ts`` for the field structure generated by ts-rs).
Field names are ``snake_case`` to match the Rust serde wire format; the few
camelCase exceptions required by the wire format (``toolName``) are handled
internally by custom serializers.
"""

from __future__ import annotations

import json
from typing import Annotated, Any, Callable, Dict, Iterator, List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel, model_serializer, model_validator

from . import _repair
from .aimux import Model

__all__ = [
    # type aliases
    "Role",
    "FinishReasonUnified",
    "ReasoningEffort",
    "MessageContent",
    "ContentPart",
    "Tool",
    "ToolChoice",
    "ResponseFormat",
    "StreamPart",
    "GenerateContent",
    "FileData",
    "FileBytes",
    "Warning",
    "AiMuxErrorValue",
    # models
    "TokenUsage",
    "Usage",
    "FinishReason",
    "ResponseMetadata",
    "ToolCall",
    "RawToolCall",
    "ToolCallRepairContext",
    "RepairToolCall",
    "ModelMessage",
    "FunctionTool",
    "ProviderTool",
    "TextContentPart",
    "GenerateTextOptions",
    "GenerateTextResult",
    "GenerateObjectResult",
    "StreamTextResultAggregated",
    "GenerateResult",
    # functions
    "generate_text",
    "stream_text",
    "parse_stream_part",
    # OpenAI Chat Completions output (RFC-0026)
    "ChatCompletion",
    "ChatCompletionChoice",
    "ChatCompletionMessage",
    "ChatCompletionToolCall",
    "ChatCompletionFunction",
    "ChatCompletionUsage",
    "ChatCompletionChunk",
    "ChatCompletionChunkChoice",
    "ChatCompletionDelta",
    "ChatCompletionChunkToolCall",
    "ChatCompletionChunkFunction",
    "PromptTokensDetails",
    "CompletionTokensDetails",
    "generate_text_as_openai",
    "stream_text_as_openai",
]


# ─────────────────────────────────────────────────────────────────────────────
# String-literal type aliases (mirror serde rename rules)
# ─────────────────────────────────────────────────────────────────────────────

#: Message sender. Rust ``Role`` serializes as lowercase strings.
Role = Literal["system", "user", "assistant", "tool"]

#: Unified finish reason. Rust ``FinishReasonUnified`` uses ``kebab-case``.
FinishReasonUnified = Literal[
    "stop", "length", "content-filter", "tool-calls", "error", "other"
]

#: Reasoning effort. Rust ``ReasoningEffort`` uses ``kebab-case``.
ReasoningEffort = Literal[
    "provider-default", "none", "minimal", "low", "medium", "high", "xhigh"
]

#: Opaque provider error value (Rust ``AiMuxError``). A mixed newtype/struct
#: externally-tagged enum, so it is left as an arbitrary JSON value rather than
#: a discriminated union. Named ``AiMuxErrorValue`` to avoid confusion with the
#: raised ``AimuxError`` exception.
AiMuxErrorValue = Any


# ─────────────────────────────────────────────────────────────────────────────
# Simple struct models
# ─────────────────────────────────────────────────────────────────────────────

class TokenUsage(BaseModel):
    """Token usage detail with cache breakdown (Rust ``TokenUsage``)."""

    total: Optional[int] = None
    no_cache: Optional[int] = None
    cache_read: Optional[int] = None
    cache_write: Optional[int] = None
    text: Optional[int] = None
    reasoning: Optional[int] = None


class Usage(BaseModel):
    """Token usage statistics (Rust ``Usage``)."""

    input_tokens: TokenUsage = Field(default_factory=TokenUsage)
    output_tokens: TokenUsage = Field(default_factory=TokenUsage)
    raw: Optional[Any] = None


class FinishReason(BaseModel):
    """Why generation stopped (Rust ``FinishReason``)."""

    unified: FinishReasonUnified
    raw: Optional[str] = None


class ResponseMetadata(BaseModel):
    """Metadata about the API response (Rust ``ResponseMetadata``)."""

    id: Optional[str] = None
    timestamp: Optional[str] = None
    model_id: Optional[str] = None


class ToolCall(BaseModel):
    """A tool call requested by the model (Rust ``tool::ToolCall``)."""

    tool_call_id: str
    tool_name: str
    input: Any
    provider_executed: Optional[bool] = None
    dynamic: Optional[bool] = None
    thought_signature: Optional[str] = None
    provider_metadata: Optional[Any] = None
    invalid: Optional[bool] = None
    error: Optional[AiMuxErrorValue] = None


class RawToolCall(BaseModel):
    """A tool call as the provider emitted it (Rust ``RawToolCall``).

    Unlike :class:`ToolCall`, ``input`` is the **raw argument text** — the
    string the model produced, parsed by nobody yet. This is both what a
    repair function is shown and what it returns.
    """

    tool_call_id: str
    tool_name: str
    input: str
    provider_executed: Optional[bool] = None
    dynamic: Optional[bool] = None
    thought_signature: Optional[str] = None
    provider_metadata: Optional[Any] = None


# ─────────────────────────────────────────────────────────────────────────────
# External-tag enums (Rust serde default for enums)
#
# Rust serializes these as ``{"Variant": {fields}}``. Pydantic discriminated
# unions use an *internal* tag, so each enum is modelled as a ``RootModel``
# over a discriminated union with a ``type`` field, plus a before-validator
# that converts the external tag into the internal discriminator and a wrap
# serializer that converts it back.
# ─────────────────────────────────────────────────────────────────────────────

def _external_tag_before(data: Any) -> Any:
    """Convert ``{"Variant": {payload}}`` → ``{"type": "Variant", **payload}``.

    Passes other shapes through unchanged (so already-internal-tagged data and
    scalars still validate).
    """
    if isinstance(data, dict) and len(data) == 1:
        (tag, payload), = data.items()
        if isinstance(payload, dict):
            return {"type": tag, **payload}
    return data


def _external_tag_serializer(out: Any) -> Any:
    """Convert ``{"type": "Variant", **fields}`` → ``{"Variant": {fields}}``."""
    if isinstance(out, dict) and "type" in out:
        tag = out.pop("type")
        return {tag: out}
    return out


# ── Warning ──────────────────────────────────────────────────────────────────

class _WarningUnsupported(BaseModel):
    type: Literal["Unsupported"]
    feature: str
    details: Optional[str] = None


class _WarningCompatibility(BaseModel):
    type: Literal["Compatibility"]
    feature: str
    details: Optional[str] = None


class _WarningDeprecated(BaseModel):
    type: Literal["Deprecated"]
    setting: str
    message: str


class _WarningOther(BaseModel):
    type: Literal["Other"]
    message: str


_WarningUnion = Annotated[
    Union[
        _WarningUnsupported,
        _WarningCompatibility,
        _WarningDeprecated,
        _WarningOther,
    ],
    Field(discriminator="type"),
]


class Warning(RootModel[_WarningUnion]):
    """A provider warning (Rust ``Warning``)."""

    root: _WarningUnion

    @model_validator(mode="before")
    @classmethod
    def _ext_to_int(cls, data: Any) -> Any:
        return _external_tag_before(data)

    @model_serializer(mode="wrap")
    def _int_to_ext(self, handler):  # type: ignore[no-untyped-def]
        return _external_tag_serializer(handler(self))


# ── FileBytes / FileData ────────────────────────────────────────────────────
#
# ``FileBytes`` and ``FileData`` are externally tagged Rust enums.
# ``FileData``'s variants are struct variants (dict payloads), so it reuses the
# shared ``_external_tag_before`` / ``_external_tag_serializer`` helpers.
# ``FileBytes`` are newtype variants whose payload is *not* a dict
# (``{"Binary": [1, 2, 3]}`` / ``{"Base64": "..."}``), so it has a dedicated
# before-validator / serializer.

class _FileBytesBinary(BaseModel):
    type: Literal["Binary"]
    data: List[int]


class _FileBytesBase64(BaseModel):
    type: Literal["Base64"]
    data: str


_FileBytesUnion = Annotated[
    Union[
        _FileBytesBinary,
        _FileBytesBase64,
    ],
    Field(discriminator="type"),
]


class FileBytes(RootModel[_FileBytesUnion]):
    """Raw bytes or a base64-encoded string (Rust ``FileBytes``).

    Wire form: ``{"Binary": [1, 2, 3]}`` / ``{"Base64": "..."}``.
    """

    root: _FileBytesUnion

    @model_validator(mode="before")
    @classmethod
    def _ext_to_int(cls, data: Any) -> Any:
        # {"Binary": [1, 2, 3]} → {"type": "Binary", "data": [1, 2, 3]}
        # {"Base64": "x"}         → {"type": "Base64", "data": "x"}
        if isinstance(data, dict) and len(data) == 1:
            (tag, payload), = data.items()
            return {"type": tag, "data": payload}
        return data

    @model_serializer(mode="wrap")
    def _int_to_ext(self, handler):  # type: ignore[no-untyped-def]
        out = handler(self)
        if isinstance(out, dict) and "type" in out and "data" in out:
            return {out["type"]: out["data"]}
        return out


class _FileDataData(BaseModel):
    type: Literal["Data"]
    data: FileBytes


class _FileDataUrl(BaseModel):
    type: Literal["Url"]
    url: str


class _FileDataReference(BaseModel):
    type: Literal["Reference"]
    reference: Dict[str, str]


class _FileDataText(BaseModel):
    type: Literal["Text"]
    text: str


_FileDataUnion = Annotated[
    Union[
        _FileDataData,
        _FileDataUrl,
        _FileDataReference,
        _FileDataText,
    ],
    Field(discriminator="type"),
]


class FileData(RootModel[_FileDataUnion]):
    """File data as a tagged union (Rust ``FileData``).

    Wire form: ``{"Data": {"data": <FileBytes>}}``, ``{"Url": {"url": "..."}}``,
    ``{"Reference": {"reference": {...}}}``, ``{"Text": {"text": "..."}}``.
    """

    root: _FileDataUnion

    @model_validator(mode="before")
    @classmethod
    def _ext_to_int(cls, data: Any) -> Any:
        return _external_tag_before(data)

    @model_serializer(mode="wrap")
    def _int_to_ext(self, handler):  # type: ignore[no-untyped-def]
        return _external_tag_serializer(handler(self))


# ── GenerateContent ─────────────────────────────────────────────────────────

class _ContentText(BaseModel):
    type: Literal["Text"]
    text: str
    provider_metadata: Optional[Dict[str, Any]] = None


class _ContentToolCall(BaseModel):
    type: Literal["ToolCall"]
    tool_call_id: str
    tool_name: str
    input: Any
    provider_executed: Optional[bool] = None
    dynamic: Optional[bool] = None
    thought_signature: Optional[str] = None
    provider_metadata: Optional[Any] = None


class _ContentSource(BaseModel):
    type: Literal["Source"]
    id: str
    source_type: str
    url: Optional[str] = None
    title: Optional[str] = None
    provider_metadata: Optional[Dict[str, Any]] = None


class _ContentReasoning(BaseModel):
    type: Literal["Reasoning"]
    text: str
    provider_metadata: Optional[Any] = None


class _ContentFile(BaseModel):
    type: Literal["File"]
    data: FileData
    media_type: str
    provider_metadata: Optional[Dict[str, Any]] = None


class _ContentToolResult(BaseModel):
    type: Literal["ToolResult"]
    tool_call_id: str
    tool_name: str
    result: Any
    is_error: Optional[bool] = None
    preliminary: Optional[bool] = None
    dynamic: Optional[bool] = None
    provider_metadata: Optional[Any] = None


_GenerateContentUnion = Annotated[
    Union[
        _ContentText,
        _ContentToolCall,
        _ContentSource,
        _ContentReasoning,
        _ContentFile,
        _ContentToolResult,
    ],
    Field(discriminator="type"),
]


class GenerateContent(RootModel[_GenerateContentUnion]):
    """A content item in the generation result (Rust ``GenerateContent``)."""

    root: _GenerateContentUnion

    @model_validator(mode="before")
    @classmethod
    def _ext_to_int(cls, data: Any) -> Any:
        return _external_tag_before(data)

    @model_serializer(mode="wrap")
    def _int_to_ext(self, handler):  # type: ignore[no-untyped-def]
        return _external_tag_serializer(handler(self))


# ── StreamPart ───────────────────────────────────────────────────────────────

class _SPTextStart(BaseModel):
    type: Literal["TextStart"]
    id: str
    provider_metadata: Optional[Dict[str, Any]] = None


class _SPTextDelta(BaseModel):
    type: Literal["TextDelta"]
    id: str
    delta: str
    provider_metadata: Optional[Dict[str, Any]] = None


class _SPTextEnd(BaseModel):
    type: Literal["TextEnd"]
    id: str
    provider_metadata: Optional[Dict[str, Any]] = None


class _SPStreamStart(BaseModel):
    type: Literal["StreamStart"]
    warnings: List[Warning]


class _SPFinish(BaseModel):
    type: Literal["Finish"]
    finish_reason: FinishReason
    usage: Usage
    provider_metadata: Optional[Any] = None


class _SPError(BaseModel):
    type: Literal["Error"]
    error: Any  # AiMuxErrorValue


class _SPToolInputStart(BaseModel):
    type: Literal["ToolInputStart"]
    id: str
    tool_name: str
    provider_executed: Optional[bool] = None
    dynamic: Optional[bool] = None
    title: Optional[str] = None
    provider_metadata: Optional[Dict[str, Any]] = None


class _SPToolInputDelta(BaseModel):
    type: Literal["ToolInputDelta"]
    id: str
    delta: str
    provider_metadata: Optional[Dict[str, Any]] = None


class _SPToolInputEnd(BaseModel):
    type: Literal["ToolInputEnd"]
    id: str
    provider_metadata: Optional[Dict[str, Any]] = None


class _SPToolCall(BaseModel):
    type: Literal["ToolCall"]
    tool_call_id: str
    tool_name: str
    input: Any
    provider_executed: Optional[bool] = None
    dynamic: Optional[bool] = None
    thought_signature: Optional[str] = None
    provider_metadata: Optional[Dict[str, Any]] = None
    invalid: Optional[bool] = None
    error: Optional[AiMuxErrorValue] = None


class _SPToolResult(BaseModel):
    type: Literal["ToolResult"]
    tool_call_id: str
    tool_name: str
    result: Any
    is_error: Optional[bool] = None
    preliminary: Optional[bool] = None
    dynamic: Optional[bool] = None
    provider_metadata: Optional[Dict[str, Any]] = None


class _SPReasoningStart(BaseModel):
    type: Literal["ReasoningStart"]
    id: str
    provider_metadata: Optional[Any] = None


class _SPReasoningDelta(BaseModel):
    type: Literal["ReasoningDelta"]
    id: str
    delta: str
    provider_metadata: Optional[Any] = None


class _SPReasoningEnd(BaseModel):
    type: Literal["ReasoningEnd"]
    id: str
    provider_metadata: Optional[Any] = None


class _SPResponseMetadata(BaseModel):
    type: Literal["ResponseMetadata"]
    id: Optional[str] = None
    timestamp: Optional[str] = None
    model_id: Optional[str] = None


class _SPSource(BaseModel):
    type: Literal["Source"]
    id: str
    source_type: str
    url: Optional[str] = None
    title: Optional[str] = None
    provider_metadata: Optional[Dict[str, Any]] = None


class _SPRaw(BaseModel):
    type: Literal["Raw"]
    raw_value: Any


class _SPFile(BaseModel):
    type: Literal["File"]
    data: FileData
    media_type: str
    provider_metadata: Optional[Dict[str, Any]] = None


_StreamPartUnion = Annotated[
    Union[
        _SPTextStart,
        _SPTextDelta,
        _SPTextEnd,
        _SPStreamStart,
        _SPFinish,
        _SPError,
        _SPToolInputStart,
        _SPToolInputDelta,
        _SPToolInputEnd,
        _SPToolCall,
        _SPToolResult,
        _SPFile,
        _SPReasoningStart,
        _SPReasoningDelta,
        _SPReasoningEnd,
        _SPResponseMetadata,
        _SPSource,
        _SPRaw,
    ],
    Field(discriminator="type"),
]


class StreamPart(RootModel[_StreamPartUnion]):
    """A single chunk in the stream returned by ``stream_text`` (Rust ``StreamPart``).

    Externally tagged on the wire: ``{"TextDelta": {"id": ..., "delta": ...}}``.
    ``parse_stream_part`` / ``StreamPart.model_validate`` accept that shape and
    :meth:`model_dump` re-emits it.
    """

    root: _StreamPartUnion

    @model_validator(mode="before")
    @classmethod
    def _ext_to_int(cls, data: Any) -> Any:
        return _external_tag_before(data)

    @model_serializer(mode="wrap")
    def _int_to_ext(self, handler):  # type: ignore[no-untyped-def]
        return _external_tag_serializer(handler(self))


# ─────────────────────────────────────────────────────────────────────────────
# ResponseFormat — external-tag enum with a unit variant (``"Text"``)
# ─────────────────────────────────────────────────────────────────────────────

class _ResponseFormatJsonBody(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    schema_: Optional[Any] = Field(default=None, alias="schema")
    name: Optional[str] = None
    description: Optional[str] = None


class ResponseFormat(RootModel[Union[Literal["Text"], _ResponseFormatJsonBody]]):
    """How the model should format its response (Rust ``ResponseFormat``).

    Wire format: ``"Text"`` or ``{"Json": {"schema": ..., "name": ..., "description": ...}}``.
    """

    root: Union[Literal["Text"], _ResponseFormatJsonBody]

    @model_validator(mode="before")
    @classmethod
    def _unwrap(cls, data: Any) -> Any:
        if isinstance(data, dict) and len(data) == 1:
            (tag, payload), = data.items()
            if tag == "Text":
                return "Text"
            if tag == "Json":
                return payload if isinstance(payload, dict) else {}
        return data

    @model_serializer(mode="wrap")
    def _ser(self, handler):  # type: ignore[no-untyped-def]
        out = handler(self)
        if isinstance(out, dict):
            return {"Json": out}
        return out  # bare "Text"


# ─────────────────────────────────────────────────────────────────────────────
# Internal-tag enums (Rust ``#[serde(tag = "type", rename_all = "snake_case")]``)
# These are already internal-tagged on the wire, so a standard discriminated
# union with a ``type`` discriminator works directly.
# ─────────────────────────────────────────────────────────────────────────────

class FunctionTool(BaseModel):
    """A user-defined function tool (Rust ``FunctionTool``)."""

    type: Literal["function"] = "function"
    name: str
    description: Optional[str] = None
    input_schema: Any
    strict: Optional[bool] = None
    provider_options: Optional[Dict[str, Any]] = None
    input_examples: Optional[List[Any]] = None


class ProviderTool(BaseModel):
    """A provider-defined tool (Rust ``ProviderTool``)."""

    type: Literal["provider"] = "provider"
    id: str
    name: str
    args: Any


Tool = Annotated[
    Union[FunctionTool, ProviderTool],
    Field(discriminator="type"),
]


# ── ContentPart (internal tag ``type``, snake_case variants) ────────────────

class TextContentPart(BaseModel):
    """A text content part (Rust ``ContentPart::Text``)."""

    type: Literal["text"] = "text"
    text: str
    provider_options: Optional[Any] = None


class _ImageContentPart(BaseModel):
    type: Literal["image"] = "image"
    image: List[int]
    media_type: str
    provider_options: Optional[Any] = None


class _FileContentPart(BaseModel):
    type: Literal["file"] = "file"
    data: List[int]
    media_type: str
    filename: Optional[str] = None
    provider_options: Optional[Any] = None


class _FileBase64ContentPart(BaseModel):
    type: Literal["file_base64"] = "file_base64"
    data: str
    media_type: str
    filename: Optional[str] = None
    provider_options: Optional[Any] = None


class _FileUrlContentPart(BaseModel):
    type: Literal["file_url"] = "file_url"
    url: str
    media_type: str
    provider_options: Optional[Any] = None


class _FileReferenceContentPart(BaseModel):
    type: Literal["file_reference"] = "file_reference"
    media_type: str
    reference: Any
    filename: Optional[str] = None
    provider_options: Optional[Any] = None


class _ReasoningContentPart(BaseModel):
    type: Literal["reasoning"] = "reasoning"
    text: str
    signature: Optional[str] = None
    provider_options: Optional[Any] = None


class _ToolCallContentPart(BaseModel):
    type: Literal["tool_call"] = "tool_call"
    tool_call_id: str
    tool_name: str
    input: Any
    provider_executed: Optional[bool] = None
    thought_signature: Optional[str] = None
    provider_options: Optional[Any] = None


class _ToolResultContentPart(BaseModel):
    type: Literal["tool_result"] = "tool_result"
    tool_call_id: str
    result: Any
    tool_name: Optional[str] = None
    is_error: Optional[bool] = None
    preliminary: Optional[bool] = None
    dynamic: Optional[bool] = None
    provider_options: Optional[Any] = None


ContentPart = Annotated[
    Union[
        TextContentPart,
        _ImageContentPart,
        _FileContentPart,
        _FileBase64ContentPart,
        _FileUrlContentPart,
        _FileReferenceContentPart,
        _ReasoningContentPart,
        _ToolCallContentPart,
        _ToolResultContentPart,
    ],
    Field(discriminator="type"),
]


#: Message body: a plain string or multi-part content (Rust ``MessageContent``).
MessageContent = Union[str, List[ContentPart]]


# ─────────────────────────────────────────────────────────────────────────────
# ToolChoice — mixed tagged/untagged enum
# Wire: ``"auto" | "none" | "required" | {"type": "tool", "toolName": "..."}``.
# Note the camelCase ``toolName`` (hand-rolled serde on the Rust side).
# ─────────────────────────────────────────────────────────────────────────────

class ToolChoiceTool(BaseModel):
    """The ``tool`` tool-choice variant (forces a specific tool)."""

    type: Literal["tool"] = "tool"
    tool_name: str

    @model_validator(mode="before")
    @classmethod
    def _accept_camel(cls, data: Any) -> Any:
        if isinstance(data, dict) and "toolName" in data and "tool_name" not in data:
            data = {**data, "tool_name": data.pop("toolName")}
        return data

    @model_serializer(mode="wrap")
    def _emit_camel(self, handler):  # type: ignore[no-untyped-def]
        out = handler(self)
        if isinstance(out, dict):
            out["toolName"] = out.pop("tool_name", None)
        return out


ToolChoice = Union[Literal["auto", "none", "required"], ToolChoiceTool]


# ─────────────────────────────────────────────────────────────────────────────
# User-facing prompt / message models
# ─────────────────────────────────────────────────────────────────────────────

class ModelMessage(BaseModel):
    """A single user-facing chat message (Rust ``ModelMessage``).

    ``content`` is untagged on the wire: a bare string or a list of content
    parts.
    """

    role: Role
    content: MessageContent


# ─────────────────────────────────────────────────────────────────────────────
# Options + results
# ─────────────────────────────────────────────────────────────────────────────

class TimeoutConfiguration(BaseModel):
    """Per-call timeout configuration (Rust ``TimeoutConfiguration``).

    All values are milliseconds; ``None`` disables the corresponding limit.
    """

    total_ms: Optional[int] = None
    step_ms: Optional[int] = None
    first_chunk_ms: Optional[int] = None
    chunk_ms: Optional[int] = None


class ToolCallRepairContext(BaseModel):
    """What a ``repair_tool_call`` function is given (RFC-0035).

    Mirrors the AI SDK ``repairToolCall`` argument: the offending call with its
    raw argument text, the error it failed with, the schema it was checked
    against, and the tools, messages and instructions the call was generated
    with.
    """

    tool_call: RawToolCall
    error: AiMuxErrorValue
    input_schema: Any = None
    tools: List[Tool] = Field(default_factory=list)
    messages: List[ModelMessage] = Field(default_factory=list)
    instructions: Optional[str] = None


#: A ``repair_tool_call`` function: return a replacement :class:`RawToolCall`
#: to re-validate, or ``None`` to leave the call invalid. Raising marks the
#: repair failed, with the exception message as the cause.
RepairToolCall = Callable[[ToolCallRepairContext], Optional[RawToolCall]]


class GenerateTextOptions(BaseModel):
    """User-facing options for ``generate_text`` / ``stream_text``.

    Mirrors Rust ``GenerateTextOptions``. All fields are optional; unset fields
    default to ``None`` (Rust treats absent / ``null`` as ``None``).

    Invalid tool calls arrive with ``invalid``/``error`` set on the tool call;
    set :attr:`repair_tool_call` to get a shot at fixing them.
    """

    max_output_tokens: Optional[int] = None
    temperature: Optional[float] = None
    stop_sequences: Optional[List[str]] = None
    top_p: Optional[float] = None
    top_k: Optional[float] = None
    presence_penalty: Optional[float] = None
    frequency_penalty: Optional[float] = None
    response_format: Optional[ResponseFormat] = None
    seed: Optional[int] = None
    tools: Optional[List[Tool]] = None
    tool_choice: Optional[ToolChoice] = None
    headers: Optional[Dict[str, str]] = None
    provider_options: Optional[Dict[str, Any]] = None
    reasoning: Optional[ReasoningEffort] = None
    instructions: Optional[str] = None
    body_overrides: Optional[Any] = None
    max_retries: Optional[int] = None
    session_id: Optional[str] = None
    """Session identifier (RFC-0024): groups consecutive calls into a session.

    Explicit values take precedence; when ``None`` and the optional session
    inferer is enabled (``init_session_infer(True)`` or ``AIMUX_SESSION_INFER=1``),
    one may be inferred from prompt-prefix continuation.
    """
    timeout: Optional[TimeoutConfiguration] = None
    include_raw_chunks: Optional[bool] = None

    repair_tool_call: Optional[RepairToolCall] = Field(default=None, exclude=True)
    """One-shot repair for tool calls that came back ``invalid`` (RFC-0035).

    Called once per invalid call, after generation and before the result is
    decoded, with a :class:`ToolCallRepairContext`. Return a
    :class:`RawToolCall` to re-validate, or ``None`` to leave the call as it
    is; raising marks the repair failed and the call keeps its original error
    with the exception message as the cause.

    It runs outside the native call and may itself call back into aimux (e.g.
    ask a model to rewrite the arguments). A call generated without ``tools``
    is never repaired. ``generate_text_as_openai`` repairs the native result
    before converting it; ``stream_text_as_openai`` does not reflect repair
    (its tool-argument deltas are the provider's text, as in the AI SDK).
    Only an exception raised by this function means "failed"; returning
    something other than a :class:`RawToolCall` or ``None`` is an error.
    Host-only: it is never serialized into the options sent across the
    boundary.
    """


class GenerateResult(BaseModel):
    """Raw provider result (Rust ``GenerateResult``), exposed via ``raw``."""

    content: List[GenerateContent]
    finish_reason: FinishReason
    usage: Usage
    warnings: List[Warning]
    provider_metadata: Optional[Any] = None
    response: ResponseMetadata
    request_body: Optional[Any] = None
    response_headers: Optional[Dict[str, str]] = None


class GenerateTextResult(BaseModel):
    """Result of ``generate_text`` (user-facing, Rust ``GenerateTextResult``)."""

    text: str
    tool_calls: List[ToolCall]
    finish_reason: FinishReason
    usage: Usage
    warnings: List[Warning]
    raw: GenerateResult
    # M7: top-level aggregation fields.
    # reasoning/sources/files use weak types (Dict) — use raw.content for
    # full typing; response_messages reuses ModelMessage for next-turn prompt.
    reasoning: List[Dict[str, Any]] = Field(default_factory=list)
    reasoning_text: str = ""
    sources: List[Dict[str, Any]] = Field(default_factory=list)
    files: List[Dict[str, Any]] = Field(default_factory=list)
    response_messages: List[ModelMessage] = Field(default_factory=list)
    # M12: raw provider-specific finish reason string (e.g. "stop", "end_turn").
    raw_finish_reason: Optional[str] = None
    # Provider-specific metadata (e.g. Anthropic cache info). Mirrored from
    # raw.provider_metadata for top-level convenience. Weak type (Dict).
    provider_metadata: Optional[Dict[str, Any]] = None
    # Response metadata (id, timestamp, model_id). Mirrored from raw.response.
    response: ResponseMetadata = Field(default_factory=ResponseMetadata)
    # Total token usage across all steps. In single-step mode (aimux's
    # default), equals usage. Provided for AI SDK parity.
    total_usage: Usage = Field(default_factory=Usage)


class GenerateObjectResult(BaseModel):
    """Result of ``generate_object`` (user-facing, M12, Rust
    ``GenerateObjectResult``). The parsed JSON object plus convenience fields
    from the underlying ``generate_text`` call.
    """

    # `object` is an arbitrary JSON value — weak type (Any).
    object: Any
    finish_reason: FinishReason
    raw_finish_reason: Optional[str] = None
    usage: Usage
    warnings: List[Warning] = Field(default_factory=list)
    # Concatenated reasoning text (if the model produced reasoning/thinking).
    reasoning: Optional[str] = None
    # Provider-specific metadata (e.g. Anthropic cache info). Weak type (Dict).
    provider_metadata: Optional[Dict[str, Any]] = None
    # Response metadata (id, timestamp, model_id).
    response: ResponseMetadata = Field(default_factory=ResponseMetadata)
    raw: GenerateTextResult


class StreamTextResultAggregated(BaseModel):
    """Aggregated result of ``stream_text().consume()`` (M11, Rust
    ``StreamTextResultAggregated``). Mirrors ``GenerateTextResult``'s
    user-facing fields (without ``raw``, since streaming has no
    ``GenerateResult`` equivalent).
    """

    text: str = ""
    # reasoning/sources/files use weak types (Dict) — same strategy as
    # GenerateTextResult.
    reasoning: List[Dict[str, Any]] = Field(default_factory=list)
    reasoning_text: str = ""
    tool_calls: List[ToolCall] = Field(default_factory=list)
    sources: List[Dict[str, Any]] = Field(default_factory=list)
    files: List[Dict[str, Any]] = Field(default_factory=list)
    finish_reason: FinishReason
    raw_finish_reason: Optional[str] = None
    usage: Usage = Usage()
    # Total token usage across all steps. In single-step mode (aimux's
    # default), equals usage. Provided for AI SDK parity.
    total_usage: Usage = Field(default_factory=Usage)
    warnings: List[Warning] = Field(default_factory=list)
    # Provider-specific metadata from the Finish chunk. Weak type (Dict).
    provider_metadata: Optional[Dict[str, Any]] = None
    # Response metadata (id, timestamp, model_id) if emitted by the stream.
    response: Optional[ResponseMetadata] = None
    response_messages: List[ModelMessage] = Field(default_factory=list)


# ─────────────────────────────────────────────────────────────────────────────
# OpenAI Chat Completions output (RFC-0026)
#
# Mirrors ``aimux_core::openai_output``. Field names match the serde wire
# format; ``skip_serializing_if = "Option::is_none"`` maps to ``Optional[...] =
# None``. The Rust field ``tool_type`` serializes as ``"type"`` (via
# ``#[serde(rename = "type")]``), so the pydantic field is named ``type``
# directly (same convention as ``FunctionTool`` above).
# ─────────────────────────────────────────────────────────────────────────────

class ChatCompletionFunction(BaseModel):
    """Function payload of a tool call (Rust ``ChatCompletionFunction``)."""

    name: str
    arguments: str


class ChatCompletionToolCall(BaseModel):
    """A tool call in an assistant message (Rust ``ChatCompletionToolCall``)."""

    id: str
    type: str
    function: ChatCompletionFunction


class ChatCompletionMessage(BaseModel):
    """The assistant message in a ChatCompletion (Rust ``ChatCompletionMessage``)."""

    role: str
    content: Optional[str] = None
    reasoning_content: Optional[str] = None
    tool_calls: Optional[List[ChatCompletionToolCall]] = None
    annotations: Optional[List[Any]] = None


class ChatCompletionChoice(BaseModel):
    """A single choice in a ChatCompletion (Rust ``ChatCompletionChoice``)."""

    index: int
    message: ChatCompletionMessage
    finish_reason: Optional[str] = None
    logprobs: Optional[Any] = None


class PromptTokensDetails(BaseModel):
    """Prompt token breakdown (Rust ``PromptTokensDetails``)."""

    cached_tokens: int
    cache_write_tokens: Optional[int] = None


class CompletionTokensDetails(BaseModel):
    """Completion token breakdown (Rust ``CompletionTokensDetails``)."""

    reasoning_tokens: Optional[int] = None


class ChatCompletionUsage(BaseModel):
    """Token usage for a Chat Completion (Rust ``ChatCompletionUsage``)."""

    prompt_tokens: int
    completion_tokens: int
    total_tokens: int
    prompt_tokens_details: Optional[PromptTokensDetails] = None
    completion_tokens_details: Optional[CompletionTokensDetails] = None


class ChatCompletion(BaseModel):
    """A complete OpenAI Chat Completion response (Rust ``ChatCompletion``)."""

    id: str
    object: str
    created: int
    model: str
    choices: List[ChatCompletionChoice]
    usage: ChatCompletionUsage
    system_fingerprint: Optional[str] = None


class ChatCompletionChunkFunction(BaseModel):
    """Function payload of a chunk tool call (Rust ``ChatCompletionChunkFunction``)."""

    name: Optional[str] = None
    arguments: Optional[str] = None


class ChatCompletionChunkToolCall(BaseModel):
    """A tool-call delta in a streaming chunk (Rust ``ChatCompletionChunkToolCall``)."""

    index: int
    id: Optional[str] = None
    type: Optional[str] = None
    function: ChatCompletionChunkFunction


class ChatCompletionDelta(BaseModel):
    """The delta payload of a streaming chunk (Rust ``ChatCompletionDelta``)."""

    role: Optional[str] = None
    content: Optional[str] = None
    reasoning_content: Optional[str] = None
    tool_calls: Optional[List[ChatCompletionChunkToolCall]] = None


class ChatCompletionChunkChoice(BaseModel):
    """A single choice in a streaming chunk (Rust ``ChatCompletionChunkChoice``)."""

    index: int
    delta: ChatCompletionDelta
    finish_reason: Optional[str] = None
    logprobs: Optional[Any] = None


class ChatCompletionChunk(BaseModel):
    """A single OpenAI Chat Completion streaming chunk (Rust ``ChatCompletionChunk``)."""

    id: str
    object: str
    created: int
    model: str
    choices: List[ChatCompletionChunkChoice]
    usage: Optional[ChatCompletionUsage] = None


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

Prompt = Union[str, List[ModelMessage], List[Dict[str, Any]]]


def _prompt_to_json(prompt: Prompt) -> str:
    """Build the JSON prompt string expected by the native layer.

    A bare string is emitted as a JSON string (→ ``ModelPrompt::Text``). A list
    of messages is wrapped as ``{"prompt": [...]}`` (→ ``ModelPrompt::Messages``).
    ``ModelMessage`` instances are serialized with ``mode="json"`` so nested
    models become JSON primitives.
    """
    if isinstance(prompt, str):
        return json.dumps(prompt)
    if not isinstance(prompt, list):
        raise TypeError(
            f"prompt must be str or list of messages, got {type(prompt).__name__}"
        )
    msgs = [
        m.model_dump(mode="json", exclude_none=True) if isinstance(m, BaseModel) else m
        for m in prompt
    ]
    return json.dumps({"prompt": msgs})


def _opts_to_json(options: Optional[GenerateTextOptions]) -> Optional[str]:
    """Serialize options to the JSON string expected by the native layer."""
    if options is None:
        return None
    if not isinstance(options, GenerateTextOptions):
        raise TypeError(
            "options must be a GenerateTextOptions instance, got "
            f"{type(options).__name__}"
        )
    # ``exclude_none`` mirrors Rust's ``#[serde(skip_serializing_if = "Option::is_none")]``
    # on the inner struct fields, producing clean payloads (absent == None for the
    # Rust deserializer). ``by_alias`` emits the ``schema`` field of the JSON
    # response-format body (and is a no-op for the snake_case fields elsewhere).
    return options.model_dump_json(exclude_none=True, by_alias=True)


def _repair_adapter(options: Optional[GenerateTextOptions]):
    """Bridge the typed repair function to the JSON-level loop in ``_repair``."""
    fn = options.repair_tool_call if options is not None else None
    if fn is None:
        return None

    def adapter(context: dict) -> Optional[dict]:
        typed = ToolCallRepairContext.model_validate(context)
        replacement = _repair.run_hook(fn, typed)
        if replacement is None:
            return None
        return replacement.model_dump(mode="json", exclude_none=True)

    return adapter


# ─────────────────────────────────────────────────────────────────────────────
# Typed API
# ─────────────────────────────────────────────────────────────────────────────

def generate_text(
    model: Model,
    prompt: Prompt,
    options: Optional[GenerateTextOptions] = None,
) -> GenerateTextResult:
    """Generate text (non-streaming), returning a typed result.

    Args:
        model: A model instance from ``openai()``, ``anthropic()``, etc.
        prompt: A string or a list of ``ModelMessage`` / message dicts.
        options: Optional typed generation options.

    Returns:
        A :class:`GenerateTextResult` with ``.text``, ``.tool_calls``,
        ``.finish_reason``, ``.usage``, ``.warnings`` and ``.raw``.
    """
    prompt_json = _prompt_to_json(prompt)
    opts_json = _opts_to_json(options)
    result_json = model.generate_text(prompt_json, opts_json)
    repair = _repair_adapter(options)
    if repair is not None:
        result_json = _repair.repair_result(result_json, prompt_json, opts_json, repair)
    return GenerateTextResult.model_validate_json(result_json)


def stream_text(
    model: Model,
    prompt: Prompt,
    options: Optional[GenerateTextOptions] = None,
) -> Iterator[dict]:
    """Stream text from a model, yielding parsed ``StreamPart`` dicts.

    Each yielded item is the external-tagged dict form produced by the Rust
    core, e.g. ``{"TextDelta": {"id": ..., "delta": ...}}``. For typed access,
    pass the dict through :func:`parse_stream_part`.

    Usage::

        for part in stream_text(model, "Write a haiku about Rust."):
            if "TextDelta" in part:
                print(part["TextDelta"]["delta"], end="")
    """
    prompt_json = _prompt_to_json(prompt)
    opts_json = _opts_to_json(options)
    repair = _repair_adapter(options)
    for part_json in model.stream_text(prompt_json, opts_json):
        if repair is not None:
            part_json = _repair.repair_stream_part(
                part_json, prompt_json, opts_json, repair
            )
        yield json.loads(part_json)


def parse_stream_part(part: dict) -> StreamPart:
    """Validate a yielded stream-part dict into a typed :class:`StreamPart`."""
    return StreamPart.model_validate(part)


def generate_text_as_openai(
    model: Model,
    prompt: Prompt,
    options: Optional[GenerateTextOptions] = None,
) -> ChatCompletion:
    """Generate text and return the result as an OpenAI Chat Completion.

    Identical to :func:`generate_text` except the result is a
    :class:`ChatCompletion` (OpenAI ``chat.completion`` object) rather than a
    :class:`GenerateTextResult`. Works with any provider.

    Args:
        model: A model instance from ``openai()``, ``anthropic()``, etc.
        prompt: A string or a list of ``ModelMessage`` / message dicts.
        options: Optional typed generation options.

    Returns:
        A :class:`ChatCompletion` with ``.id``, ``.choices``, ``.usage``, …

    With ``options.repair_tool_call``, invalid calls are repaired on the
    native result first and the completion is converted from it, so its
    ``tool_calls`` carry the repaired arguments.
    """
    prompt_json = _prompt_to_json(prompt)
    opts_json = _opts_to_json(options)
    repair = _repair_adapter(options)
    if repair is not None:
        result_json = model.generate_text(prompt_json, opts_json)
        result_json = _repair.repair_result(result_json, prompt_json, opts_json, repair)
        result_json = model.generate_text_result_as_openai(result_json)
    else:
        result_json = model.generate_text_as_openai(prompt_json, opts_json)
    return ChatCompletion.model_validate_json(result_json)


def stream_text_as_openai(
    model: Model,
    prompt: Prompt,
    options: Optional[GenerateTextOptions] = None,
) -> Iterator[ChatCompletionChunk]:
    """Stream text as OpenAI Chat Completion chunks.

    Identical to :func:`stream_text` except each yielded item is a typed
    :class:`ChatCompletionChunk` (OpenAI ``chat.completion.chunk`` object).
    Works with any provider.

    Stream options (``include_usage``, ``include_reasoning``) are read from
    ``options.provider_options.openai.stream_options`` (both default to ``True``).

    Usage::

        for chunk in stream_text_as_openai(model, "Write a haiku about Rust."):
            if chunk.choices and chunk.choices[0].delta.content:
                print(chunk.choices[0].delta.content, end="")
    """
    prompt_json = _prompt_to_json(prompt)
    opts_json = _opts_to_json(options)
    for chunk_json in model.stream_text_as_openai(prompt_json, opts_json):
        yield ChatCompletionChunk.model_validate_json(chunk_json)
