/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Fallible native return — unwraps to `T` at runtime; core failures reject/throw the registered `AimuxError` subclass, while binding faults remain napi-rs plain `Error`s. */
export type AimuxResult<T> = T
/** Stream yield — a StreamPart JSON string at runtime; failures reject `next()` with a typed error. */
export type StreamItem = string
declare global {
  interface __NapiRsAsyncGenerator<TOwner, T, TReturn, TNext> {
    next(...[value]: [] | [TNext]): globalThis.Promise<globalThis.IteratorResult<T, TReturn | undefined>>
    return(...[value]: [] | [TReturn]): globalThis.Promise<globalThis.IteratorResult<T, TReturn | undefined>>
    throw(exception?: unknown): globalThis.Promise<globalThis.IteratorResult<T, TReturn | undefined>>
    [globalThis.Symbol.asyncIterator](): this
  }
}

/**
 * A bridge from a JS `AbortSignal` to the core's runtime cancellation.
 *
 * napi's own `AbortSignal` is not `Send` (it holds `Rc`), so it cannot be a
 * parameter of an async napi method. This class is created synchronously
 * (registering the abort callback on the JS thread) and then passed to
 * `generateText` / `streamText` — it only holds an `Arc` and is `Send`.
 *
 * ```ts
 * const bridge = signal ? new AbortBridge(signal) : undefined
 * await model.generateText(prompt, options, bridge)
 * ```
 */
export declare class AbortBridge {
  constructor(signal: AbortSignal)
  /** Returns `true` once the underlying JS signal has been aborted. */
  aborted(): boolean
}

export declare class EmbeddingModel {
  /**
   * Generate embeddings. `values_json` is a JSON array of strings.
   * Returns JSON-serialized EmbeddingResult.
   */
  embed(valuesJson: string, optsJson?: string | undefined | null): Promise<string>
}

export declare class Files {
  /**
   * Upload a file. `data_base64` is base64-encoded file content,
   * `media_type` is e.g. "application/pdf", `opts_json` is optional
   * (may contain filename, provider_options).
   * Returns JSON-serialized UploadFileResult (contains provider file ID).
   */
  uploadFile(dataBase64: string, mediaType: string, optsJson?: string | undefined | null): Promise<string>
}

export declare class HostOperation {
  next(lane: number): Promise<AimuxResult<any | undefined | null>>
  reply(requestId: string, reply: any): AimuxResult<number>
  cancel(): void
  finished(): Promise<void>
  close(): Promise<void>
}

export declare class ImageModel {
  /**
   * Generate images. `opts_json` is JSON-serialized ImageCallOptions.
   * `bridge` — optional `AbortBridge`; aborting the wrapped signal cancels
   * the call. Returns JSON-serialized ImageResult (images as base64 in JSON).
   */
  generate(optsJson: string, bridge?: AbortBridge | undefined | null): Promise<string>
}

export declare class Model {
  startOperation(request: any): Promise<AimuxResult<HostOperation>>
  /**
   * Wrap this model in a cache-probe layer (RFC-0015). The returned
   * model records fingerprints/verdicts on every call and exposes the
   * `traceAggregate` / `traceSessionChain` / `traceExportJsonl` /
   * `traceClear` queries.
   */
  trace(): Model
  /**
   * Wrap this model in a cache-probe layer with the built-in rules
   * auditor (RFC-0015 §4). `strict` = strict mode (self-hosted single
   * instance); `false` = shared mode (safe default).
   */
  traceAudited(strict: boolean): Model
  /**
   * Aggregated probe statistics (RFC-0015 §5.3), filtered by a JSON
   * `TraceFilter` (optional). Returns a JSON `TraceStats[]` string.
   */
  traceAggregate(filterJson?: string | undefined | null): AimuxResult<string>
  /**
   * One session's chain view (RFC-0015 §5.3). Returns a JSON
   * `SessionChainView` string or an error when the session is unknown.
   */
  traceSessionChain(sessionId: string): AimuxResult<string>
  /**
   * One session's per-step cache-hit trajectory (RFC-0024 §4.3). Returns
   * a JSON array of `SessionStepStat` (empty when the session is unknown
   * or the model is not traced).
   */
  traceSessionTrajectory(sessionId: string): AimuxResult<string>
  /** Export all probe records as JSONL (one `TraceRecord` per line). */
  traceExportJsonl(): AimuxResult<string>
  /** Clear all probe records of this traced model. */
  traceClear(): void
  /**
   * Generate text (non-streaming).
   *
   * `prompt` — a JSON string: bare prompt (`"text"` or `[{...}]`) or `{"prompt": ...}`.
   * `options` — optional JSON-serialized `GenerateTextOptions`.
   * `bridge` — optional `AbortBridge` (wrap a JS `AbortSignal` in one);
   * aborting the signal cancels the call.
   * Returns a JSON-serialized `GenerateTextResult`.
   */
  generateText(prompt: string, options?: string | undefined | null, bridge?: AbortBridge | undefined | null): Promise<string>
  /**
   * Generate a structured JSON object from the model (M12, RFC-0016).
   *
   * Same signature as [`Model::generate_text`]; returns a JSON-serialized
   * `GenerateObjectResult`. Pass `response_format: { "Json": { ... } }`
   * via `options` for schema control; the function applies JSON repair
   * before parsing.
   */
  generateObject(prompt: string, options?: string | undefined | null, bridge?: AbortBridge | undefined | null): Promise<string>
  /**
   * Consume a stream to completion and return the aggregated result
   * (M11, RFC-0016).
   *
   * Drives `streamText` to completion and returns a JSON-serialized
   * `StreamTextResultAggregated` (the fully-consumed stream summary).
   */
  consumeStreamText(prompt: string, options?: string | undefined | null, bridge?: AbortBridge | undefined | null): Promise<string>
  /**
   * Stream text from the model.
   *
   * Returns an `AsyncGenerator<string>` yielding `StreamPart` JSON strings.
   * Use `for await (const part of model.streamText(...))` to consume.
   */
  streamText(prompt: string, options?: string | undefined | null, bridge?: AbortBridge | undefined | null): Promise<AsyncGenerator<string>>
  /**
   * Generate text and return an OpenAI Chat Completion (non-streaming).
   *
   * Returns a JSON-serialized `ChatCompletion`. Works with any provider.
   */
  generateTextAsOpenai(prompt: string, options?: string | undefined | null, bridge?: AbortBridge | undefined | null): Promise<string>
  /**
   * Stream text as OpenAI Chat Completion chunks.
   *
   * Returns an `AsyncGenerator<string>` yielding `ChatCompletionChunk` JSON
   * strings. Works with any provider.
   */
  streamTextAsOpenai(prompt: string, options?: string | undefined | null, bridge?: AbortBridge | undefined | null): Promise<AsyncGenerator<string>>
}

/**
 * A provider handle — created by `createProvider`, supports `listModels()`
 * (runtime discovery) and `model()` (build a model from a discovered id).
 *
 * ```ts
 * const p = await createProvider('deepseek', apiKey)
 * const models = await p.listModels()
 * const model = await p.model(models[0].id)
 * const result = await generateText(model, 'Hello')
 * ```
 */
export declare class ProviderHandle {
  /**
   * List models available on this provider (runtime discovery via the
   * provider's `/models` endpoint). Returns a JSON array of sparse
   * `RuntimeModel` (id / owned_by / created) — **no community enrichment**.
   * To supplement with model specs (context length, capabilities, reasoning),
   * call `getModelSpecs` separately and merge in the host (RFC-0027).
   */
  listModels(): Promise<AimuxResult<string>>
  /**
   * Build a language model from a discovered model id. Returns a `Model`
   * usable with `generateText` / `streamText`.
   */
  model(modelId: string): Promise<AimuxResult<Model>>
}

export declare class RerankingModel {
  /**
   * Rerank documents. `query` is the search query, `docs_json` is a JSON
   * array of documents, `opts_json` is optional JSON options.
   * `bridge` — optional `AbortBridge`; aborting the wrapped signal cancels
   * the call. Returns JSON-serialized RerankingResult.
   */
  rerank(query: string, docsJson: string, optsJson?: string | undefined | null, bridge?: AbortBridge | undefined | null): Promise<string>
}

export declare class SearchModel {
  /**
   * Search. `query` is the search query, `opts_json` is optional JSON options.
   * `bridge` — optional `AbortBridge`; aborting the wrapped signal cancels
   * the call. Returns JSON-serialized SearchResult.
   */
  search(query: string, optsJson?: string | undefined | null, bridge?: AbortBridge | undefined | null): Promise<string>
}

export declare class SpeechModel {
  /**
   * Generate speech audio. `opts_json` is JSON-serialized SpeechCallOptions.
   * `bridge` — optional `AbortBridge`; aborting the wrapped signal cancels
   * the call. Returns JSON-serialized SpeechResult (audio as base64 in JSON).
   */
  generate(optsJson: string, bridge?: AbortBridge | undefined | null): Promise<string>
}

/**
 * AsyncGenerator that yields StreamPart JSON strings.
 *
 * The stream is started eagerly in `stream_text()` — a tokio task drives
 * the Rust Stream and sends each chunk through a channel. `next()` simply
 * receives from the channel.
 *
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class StreamTextGenerator {

  [globalThis.Symbol.asyncIterator](): globalThis.__NapiRsAsyncGenerator<StreamTextGenerator, StreamItem, void, undefined>
}

export declare class TranscriptionModel {
  /**
   * Transcribe audio. `audio_base64` is base64-encoded audio data.
   * `media_type` is e.g. "audio/mp3". `opts_json` is optional JSON options.
   * `bridge` — optional `AbortBridge`; aborting the wrapped signal cancels
   * the call. Returns JSON-serialized TranscriptionResult.
   */
  generate(audioBase64: string, mediaType: string, optsJson?: string | undefined | null, bridge?: AbortBridge | undefined | null): Promise<string>
}

/**
 * A live streaming-transcription session (RFC-0028). Push audio chunks with
 * `pushAudio`, mark end-of-audio with `inputDone`, then pull transcription
 * parts with `nextPart`. Mirrors the C-ABI session shape, built natively on
 * core channels.
 */
export declare class TranscriptionSession {
  /**
   * Push one binary audio chunk. Awaits while the internal channel is
   * full (backpressure).
   */
  pushAudio(data: Buffer): Promise<AimuxResult<undefined>>
  /** Signal end-of-audio (idempotent). */
  inputDone(): AimuxResult<undefined>
  /**
   * Pull the next transcription part (JSON string). Resolves `null` when
   * the stream ended normally. Rejects on error — including a timeout
   * (no part within `timeoutMs`; the session stays live, call again).
   * `timeoutMs`: >0 wait at most; 0 immediate poll; negative OR omitted
   * = wait indefinitely.
   */
  nextPart(timeoutMs?: number | undefined | null): Promise<AimuxResult<string | undefined | null>>
  /**
   * Terminate the session (aborts the driver). The object becomes inert;
   * further `pushAudio`/`nextPart` fail. Call this promptly — GC teardown
   * drops the channels (which eventually tears the driver down) but never
   * fires the abort token.
   */
  close(): void
}

export declare class VideoModel {
  /**
   * Generate video. `opts_json` is JSON-serialized VideoCallOptions.
   * `bridge` — optional `AbortBridge`; aborting the wrapped signal cancels
   * the call. Returns JSON-serialized VideoResult (typically contains a URL).
   */
  generate(optsJson: string, bridge?: AbortBridge | undefined | null): Promise<string>
}

/**
 * Register the canonical JS error constructors for this Node environment.
 *
 * Keeping the constructors in the environment, rather than a process-global,
 * preserves class identity and keeps Worker environments isolated.
 */
export declare function __registerErrorClasses(constructors: object): void

/** Create an Anthropic model instance. */
export declare function anthropic(apiKey: string, modelId: string, config?: string | ProviderConfig | undefined | null): Promise<AimuxResult<Model>>

/** Create an Anthropic-on-AWS language model instance (API key + region). */
export declare function anthropicAws(apiKey: string, region: string, modelId: string, config?: string | ProviderConfig | undefined | null): Promise<AimuxResult<Model>>

/**
 * Create an Azure OpenAI language model instance (API key + resource name).
 *
 * The deployment name is passed as `model_id`; `api_version` is optional.
 */
export declare function azure(apiKey: string, resourceName: string, deployment: string, apiVersion?: string | undefined | null, config?: string | ProviderConfig | undefined | null): Promise<AimuxResult<Model>>

/** Create a Bedrock language model instance (AWS SigV4 credentials). */
export declare function bedrock(accessKeyId: string, secretAccessKey: string, region: string, modelId: string, config?: string | ProviderConfig | undefined | null): Promise<AimuxResult<Model>>

/** Create a Cohere language model instance. */
export declare function cohere(apiKey: string, modelId: string, config?: string | ProviderConfig | undefined | null): Promise<AimuxResult<Model>>

/** Create a Cohere embedding model instance. */
export declare function cohereEmbedding(apiKey: string, modelId: string, baseUrl?: string | undefined | null): Promise<AimuxResult<EmbeddingModel>>

/** Create a Cohere reranking model instance. */
export declare function cohereReranking(apiKey: string, modelId: string, baseUrl?: string | undefined | null): Promise<AimuxResult<RerankingModel>>

/**
 * Create a **provider handle** (RFC-0027) for a registry-backed provider.
 *
 * Unlike `provider()` (which binds to a single model_id), this returns a
 * `ProviderHandle` that supports `listModels()` and `model()`.
 *
 * `api_key` may be empty/null to read the provider's env var from the
 * registry entry.
 */
export declare function createProvider(name: string, apiKey?: string | undefined | null, config?: ProviderConfig | undefined | null): Promise<AimuxResult<ProviderHandle>>

/** Create a DeepSeek model instance (registry-backed since RFC-0017 phase 4). */
export declare function deepseek(apiKey: string, modelId: string, config?: string | ProviderConfig | undefined | null): Promise<AimuxResult<Model>>

/**
 * Fetch the community model catalogue (anya2a). Returns a JSON-serialized
 * `Catalogue` (provider → model_id → ModelSpec). Thin fetch — no caching.
 * `source_url` may be null for the default endpoint.
 */
export declare function getModelSpecs(sourceUrl?: string | undefined | null): Promise<AimuxResult<string>>

/**
 * Create a Google Gemini language model instance.
 *
 * Google speaks the native `generateContent` protocol (not OpenAI-compatible),
 * so it is **not** registry-backed — `provider("google", ...)` fails with
 * `NoSuchProvider`. This factory is the only entry point.
 */
export declare function google(apiKey: string, modelId: string, config?: string | ProviderConfig | undefined | null): Promise<AimuxResult<Model>>

/** Create a Google embedding model instance. */
export declare function googleEmbedding(apiKey: string, modelId: string, baseUrl?: string | undefined | null): Promise<AimuxResult<EmbeddingModel>>

/** Create a Google image model instance. */
export declare function googleImage(apiKey: string, modelId: string, baseUrl?: string | undefined | null): Promise<AimuxResult<ImageModel>>

/** Create a Google video model instance. */
export declare function googleVideo(apiKey: string, modelId: string, baseUrl?: string | undefined | null): Promise<AimuxResult<VideoModel>>

/**
 * 初始化全局日志（RFC-0014）。幂等：多次调用无副作用；宿主已自建
 * subscriber 时 no-op。级别：off|error|warn|info|debug|trace（空串回退
 * warn）。`AIMUX_LOG` / `AIMUX_LOG_LEVEL` 环境变量优先级更高。
 * 日志输出到 stderr。
 */
export declare function initLogging(level: string): void

/**
 * Set the global proxy configuration (M6, RFC-0016). Must be called before
 * the first `generateText` / `streamText` call; a no-op if the shared HTTP
 * client is already initialised (the shared client is lazily built on first
 * use and locked for the process lifetime).
 *
 * `configJson` shape: `{ "http_url": "...", "https_url": "...", "all_url":
 * "...", "no_proxy": "..." }` (all fields optional; omitting all is equivalent
 * to relying on the `HTTP_PROXY` / `HTTPS_PROXY` / `ALL_PROXY` / `NO_PROXY`
 * env vars).
 *
 * Throws on invalid JSON.
 */
export declare function initProxy(configJson: string): AimuxResult<undefined>

/**
 * 启动录制(RFC-0023 P1/P2):把完整 `Recording` 写 JSONL 到 `{dir}/recordings.jsonl`
 * (目录自动创建)。录制 **opt-in**;再次调用(不同 dir)替换 recorder。
 * Throws `RecordingError` (`code` = `Init` / `OpenFile` / `Spawn`) when the
 * recorder cannot be set up; the previous recorder, if any, stays in place.
 */
export declare function initRecording(dir: string): AimuxResult<undefined>

/**
 * 启动内存有界录制(RFC-0023 P6):`RingRecorder`,FIFO 淘汰,丢弃计数可查。
 *
 * `cap` 可省略:省略时使用库默认容量(等价于 FFI `aimux_init_recording_ring_default()`;
 * 本绑定直接依赖 aimux-core 而非 aimux-ffi,故调用等价 core API `RingRecorder::default()`)。
 * 显式传 `cap == 0` 抛错(与其余语言一致),`cap > 0` 启动指定容量的有界 ring。
 */
export declare function initRecordingRing(cap?: number | undefined | null): AimuxResult<undefined>

/**
 * Enable/disable the global session inferer (RFC-0024, opt-in, off by
 * default). Explicit `sessionId` values always win regardless of this.
 */
export declare function initSessionInfer(enabled: boolean): void

/**
 * Register the global session store (RFC-0024). Replaces any previous one.
 * Until called, calls are not grouped and the session query functions return
 * empty results.
 */
export declare function initSessionStore(): void

/** Query: all known sessions (RFC-0024), as a JSON-serialized `SessionView[]`. */
export declare function listSessions(): AimuxResult<string>

/** Create a Mistral language model instance. */
export declare function mistral(apiKey: string, modelId: string, config?: string | ProviderConfig | undefined | null): Promise<AimuxResult<Model>>

export declare function moa(references: Array<Model>, aggregator: Model, configJson?: string | undefined | null): AimuxResult<Model>

/**
 * 从录制 JSONL 创建 mock 回放模型(RFC-0023 P3):按输入匹配录制响应,
 * **不发真实 API**。返回的 `Model` 可用于 `generateText` / `streamText`。
 */
export declare function mockReplay(recordingsJsonl: string): AimuxResult<Model>

/** Create an OpenAI model instance. */
export declare function openai(apiKey: string, modelId: string, config?: string | ProviderConfig | undefined | null): Promise<AimuxResult<Model>>

/** Create an OpenAI embedding model instance. */
export declare function openaiEmbedding(apiKey: string, modelId: string, baseUrl?: string | undefined | null): Promise<AimuxResult<EmbeddingModel>>

/** Create OpenAI files manager. */
export declare function openaiFiles(apiKey: string, baseUrl?: string | undefined | null): Promise<AimuxResult<Files>>

/** Create an OpenAI image model instance. */
export declare function openaiImage(apiKey: string, modelId: string, baseUrl?: string | undefined | null): Promise<AimuxResult<ImageModel>>

/** Create an OpenAI speech (TTS) model instance. */
export declare function openaiSpeech(apiKey: string, modelId: string, baseUrl?: string | undefined | null): Promise<AimuxResult<SpeechModel>>

/** Create an OpenAI transcription model instance. */
export declare function openaiTranscription(apiKey: string, modelId: string, baseUrl?: string | undefined | null): Promise<AimuxResult<TranscriptionModel>>

/**
 * Create a language model from the built-in registry by provider name
 * (RFC-0017 phase 4). `api_key` may be empty/null to read the provider's env
 * var from the registry entry.
 */
export declare function provider(name: string, apiKey: string | undefined | null, modelId: string, config?: ProviderConfig | undefined | null): Promise<AimuxResult<Model>>

/**
 * Optional provider configuration accepted by factory functions.
 *
 * Passed as the 3rd argument to `openai()` / `anthropic()` / `deepseek()`.
 * For backward compatibility a bare string is still accepted (treated as
 * `baseUrl`). See RFC-0017.
 */
export interface ProviderConfig {
  /** Base URL for API calls (e.g. a relay/proxy endpoint). */
  baseUrl?: string
  /**
   * Extra HTTP headers merged into every request, as a JSON object string
   * (e.g. `'{"X-Custom":"value"}'`).
   */
  headers?: string
  /** OpenAI organization ID (sent via `OpenAI-Organization` header). */
  organization?: string
  /** OpenAI project ID (sent via `OpenAI-Project` header). */
  project?: string
  /** Override the provider's retry count. `0` disables retries. */
  maxRetries?: number
  /**
   * Provider-level request body overrides as a JSON string (deep-merged
   * into every request). Per-call `bodyOverrides` in GenerateTextOptions
   * takes precedence. Pass a JSON object string, e.g.
   * `'{"enable_thinking": false}'`.
   */
  bodyOverrides?: string
}

/** 刷盘全局 recorder(阻塞至 JSONL 落盘;ring 模式为 no-op)。 */
export declare function recordingFlush(): void

/** 停止录制:全局 recorder = None(新调用不再录制)。 */
export declare function recordingStop(): void

/**
 * Flush the global recorder and **report write failures**: throws
 * `RecordingError` (`code` = `WriterGone` / `FlushTimeout` / `Write`) when the
 * data could not be confirmed on disk. `RecordingError` is its own class,
 * not an `AimuxError`. Resolves normally when nothing is recording. The
 * legacy `recordingFlush` stays and never reports.
 */
export declare function recordingTryFlush(): AimuxResult<undefined>

/**
 * Register external OpenAI-compatible providers from a JSON config string
 * (RFC-0020). Entries override same-named built-ins or add new ones.
 *
 * `configJson` shape: `{ "providers": [ { "name": "...", "base_url": "...", ... } ] }`.
 * Malformed JSON text throws a plain `Error` (napi `InvalidArg`); a
 * well-formed document the registry rejects (bad base_url scheme, empty
 * name, unsupported protocol, wrong shape) throws `InvalidArgumentError`.
 */
export declare function registerProviders(configJson: string): AimuxResult<undefined>

export declare function router(models: Array<Model>, configJson?: string | undefined | null): AimuxResult<Model>

/**
 * Query: all calls of a session (RFC-0024), as a JSON-serialized
 * `SessionCall[]` (ordered by step). Empty array if the session is unknown
 * or no store is registered.
 */
export declare function sessionCalls(sessionId: string): AimuxResult<string>

/**
 * Start a streaming transcription session. `opts_json` (optional):
 * `{ "input_audio_format": {"format_type","rate"}, "provider_options",
 * "headers", "include_raw_chunks" }`. `bridge` — optional AbortSignal; firing
 * it aborts the session. The returned parts are JSON-serialized
 * `TranscriptionStreamPart`s.
 */
export declare function startTranscriptionSession(model: TranscriptionModel, optsJson?: string | undefined | null, bridge?: AbortBridge | undefined | null): Promise<AimuxResult<TranscriptionSession>>

/** Create a Tavily search model instance. */
export declare function tavilySearch(apiKey: string, baseUrl?: string | undefined | null): Promise<AimuxResult<SearchModel>>

/** Create a Vertex AI language model instance (GCP bearer token). */
export declare function vertex(accessToken: string, project: string, location: string, modelId: string, config?: string | ProviderConfig | undefined | null): Promise<AimuxResult<Model>>

/** Create an xAI language model instance. */
export declare function xai(apiKey: string, modelId: string, config?: string | ProviderConfig | undefined | null): Promise<AimuxResult<Model>>
